package com.binus.pekalongancityguide.ItemList;

public class ConvoItem {

    public static String[] name = {
            "Tommy",
            "Budi",
            "Tommy",
            "Budi & Tommy",
            "Pak Gembus",
            "Budi",
            "Tommy",
            "Pak Gembus",
            "Budi & Tommy",
            "Tommy",
            "Budi",
            "Tommy",
            "Budi & Tommy",
            "Pak Andi",
            "Budi",
            "Pak Andi",
            "Tommy",
            "Pak Andi",
            "Budi & Tommy",
            "Pak Gembus",
            "Budi",
            "Tommy",
            "Budi"
    };

    public static String[] aksara = {
            "ꦢꦶꦤ꧀ꦠꦺꦤ꧀ꦥꦸꦤꦶꦏꦶꦄꦗꦺꦁꦤꦺꦣꦥꦸꦤꦥꦧꦸꦢꦶ?",
            "ꦏꦸꦭꦧꦣꦺꦤꦺꦣꦄꦪꦩ꧀ꦒꦺꦴꦫꦺꦁꦥꦏ꧀ꦒꦺꦩ꧀ꦧꦸꦱ꧀",
            "ꦱꦶꦪꦥ꧀\u200Cꦠꦺꦁꦒꦏꦸꦭꦄꦢꦸꦱ꧀ꦱꦺꦏꦺꦣꦥ꧀",
            "ꦱꦸꦒꦺꦁꦱꦶꦪꦁꦥꦏ꧀꧈ꦏꦢꦺꦴꦱ꧀ꦥꦸꦤ꧀ꦢꦶꦏꦧꦫꦶꦥꦸꦤ꧀?",
            "ꦱꦌ-ꦱꦌꦩꦮꦺꦴꦤ꧀ꦤꦏ꧀꧈ꦩꦁꦒꦩ꧀ꦭꦺꦧꦺꦠ꧀",
            "ꦏꦸꦭꦧꦣꦺꦣꦣꦠꦩ꧀ꦧꦃꦏꦺꦴꦭ꧀ꦒꦺꦴꦫꦺꦁꦥꦏ꧀",
            "ꦏꦸꦭꦥꦺꦱꦺꦤ꧀ꦆꦁꦏꦁꦱꦩꦶꦏꦭꦶꦪꦤ꧀ꦱꦩ꧀ꦧꦺꦭ꧀ꦆꦁꦏꦁꦏꦛꦃꦔ꧀ꦒꦶꦃꦥꦏ꧀",
            "ꦱꦌꦤꦏ꧀꧈ꦠꦺꦁꦒ꧇꧑꧐꧇ꦩꦺꦤꦶꦠ꧀ꦔ꧀ꦒꦶꦃ꧈ꦤꦱꦶꦤꦶꦥꦸꦤ꧀ꦢꦺꦫꦺꦁꦩꦱꦏ꧀",
            "ꦔ꧀ꦒꦶꦃꦥꦏ꧀\u200Cꦏꦶꦠꦩꦺꦢꦭ꧀ꦫꦸꦩꦶꦪꦶꦤ꧀ꦏꦁꦒꦺꦠꦸꦩ꧀ꦧꦱ꧀ꦧꦫꦁ",
            "ꦧꦸꦢꦶꦕꦺꦴꦧꦶꦠꦶꦔꦭ꧀ꦧꦫꦁꦥꦸꦤꦶꦏꦶꦱꦌꦔ꧀ꦒꦶꦃ",
            "ꦏꦸꦭꦏꦭ-ꦮꦈꦏꦺꦥꦁꦒꦶꦃꦧꦫꦁꦥꦸꦤꦶꦏꦶꦭꦁꦏꦸꦁꦱꦌ",
            "ꦎꦏꦺ꧈ꦏꦶꦠꦠꦸꦩ꧀ꦧꦱ꧀ꦆꦁꦏꦁꦥꦸꦤꦶꦏꦸꦩꦮꦺꦴꦤ꧀",
            "ꦥꦏ꧀\u200Cꦏꦶꦠꦧꦣꦺꦠꦸꦩ꧀ꦧꦱ꧀ꦥꦸꦤꦶꦏꦶ꧉ꦥꦶꦤ꧀ꦠꦺꦤ꧀ꦫꦺꦒꦶꦤꦶꦥꦸꦤ꧀ꦔ꧀ꦒꦶꦃ?",
            "ꦫꦺꦒꦶꦤꦶꦥꦸꦤ꧀ꦱꦺꦏꦺꦠ꧀ꦌꦮꦸꦫꦸꦥꦶꦪꦃ",
            "ꦱꦒꦺꦢ꧀ꦤꦺꦣꦢꦶꦱ꧀ꦏꦺꦴꦤ꧀ꦥꦏ꧀?",
            "ꦩ꧀ꦧꦺꦴꦠꦺꦤ꧀ꦱꦒꦺꦢ꧀ꦤꦏ꧀\u200Cꦥꦸꦤꦶꦏꦶꦫꦺꦒꦶꦤꦶꦥꦸꦤ꧀ꦱꦩ꧀ꦥꦸꦤ꧀ꦱꦌ",
            "ꦔ꧀ꦒꦶꦃꦥꦏ꧀\u200Cꦥꦸꦤꦶꦏꦶꦄꦂꦠꦤꦶꦥꦸꦤ꧀ꦥꦶꦠꦸꦁꦢꦱꦒꦁꦱꦭ꧀ꦌꦮꦸꦫꦶꦥꦸꦮꦃ",
            "ꦥꦸꦤꦶꦏꦶꦱꦸꦱꦸꦏꦶꦥꦸꦤ꧀ꦔ꧀ꦒꦶꦃꦤꦏ꧀\u200Cꦩꦠꦸꦂꦤꦸꦮꦸꦤ꧀",
            "ꦩꦠꦸꦂꦤꦸꦮꦸꦤ꧀ꦥꦏ꧀",
            "ꦥꦸꦤꦶꦏꦶꦩꦏꦤꦤꦶꦥꦸꦤ꧀ꦔ꧀ꦒꦶꦃꦤꦏ꧀",
            "ꦢꦶꦤ꧀ꦠꦺꦤ꧀ꦥꦸꦤꦶꦏꦶꦄꦪꦩꦶꦥꦸꦤ꧀ꦌꦕꦥꦶꦱꦤ꧀ꦔ꧀ꦒꦶꦃ",
            "ꦔ꧀ꦒꦶꦃꦭꦺꦫꦺꦱ꧀",
            "ꦥꦸꦤꦶꦏꦶꦄꦂꦠꦤꦶꦥꦸꦤ꧀ꦔ꧀ꦒꦶꦃꦥꦏ꧀\u200Cꦩꦠꦸꦂꦤꦸꦮꦸꦤ꧀"
    };

    public static String[] latinText = {
            "dinten puniki ajeng nedha punapa budi?",
            "kula badhe nedha ayam goreng pak gembus",
            "siap, tengga kula adus sekedhap",
            "sugeng siyang pak. kados pundi kabaripun?",
            "sae-sae mawon nak. mangga mlebet",
            "kula badhe dhadha tambah kol goreng pak",
            "kula pesen ingkang sami kaliyan sambel ingkang kathah nggih pak",
            "sae nak. Tengga 10 menit nggih, nasinipun dereng masak",
            "nggih pak, kita medal rumiyin kangge tumbas barang",
            "budi cobi tingal barang puniki sae nggih",
            "kula kala-wau kepanggih barang puniki langkung sae",
            "oke, kita tumbas ingkang puniku mawon",
            "pak, kita badhe tumbas puniki. pinten reginipun nggih?",
            "reginipun seket ewu rupiyah",
            "saged nedha diskon pak?",
            "mboten saged nak, puniki reginipun sampun sae",
            "nggih pak, puniki artanipun pitung dasa gangsal ewu ripuah",
            "puniki susukipun nggih nak, matur nuwun",
            "matur nuwun pak",
            "puniki makananipun nggih nak",
            "dinten puniki ayamipun eca pisan nggih",
            "nggih leres",
            "puniki artanipun nggih pak, matur nuwun"
    };

    public static String[] engText = {
            "What do you want to eat today, Budi ?",
            "I want to eat Pak Gembus fried Chicken",
            "Got it, wait im gonna take a bath",
            "Good Afternoon sir, how are you?",
            "Im good. Come on in",
            "I want chicken breast with fried cabbage sir",
            "I want the same with more sambal sir",
            "Okay kid. Please wait 10 minutes, the rice is not cooked yet",
            "Okay sir, we want to buy some items outside",
            "Budi look this item is pretty good",
            "I found this item is better",
            "okay, we should buy that one then",
            "Sir, we want to buy this. How much is it?",
            "It is fifty thousand rupiah kid",
            "Can we ask for discount sir?",
            "No kid, the price is already good",
            "Okay sir, here is seventy five thousand rupiah",
            "here is the change kid, thank you",
            "Thanks sir",
            "Here is the food kid",
            "Today the chicken is so good",
            "That's right",
            "here is the money sir, thank you"
    };

    public static String[] indoText = {
            "hari ini mau makan apa budi ?",
            "saya ingin makan ayam goreng pak Gembus",
            "siap, tunggu saya mandi sebentar",
            "selamat siang pak. Bagaimana kabarnya?",
            "baik - baik saja nak. Silahkan masuk ",
            "saya mau dada tambah kol goreng pak",
            "saya pesan yang sama dengan sambal yang banyak ya pak",
            "baik nak. Tunggu 10 menit ya, nasinya belum masak",
            "Baik pak, kami keluar dulu untuk beli barang",
            "Budi coba lihat barang ini bagus ya ",
            "saya tadi ketemu barang ini lebih bagus",
            "oke, kita beli yang itu saja",
            "Pak, kami mau beli ini. Berapa harganya ya ?",
            "Harganya lima puluh ribu rupiah",
            "Bisa minta diskon pak ?",
            "Tidak bisa nak, ini harganya sudah bagus",
            "baik pak, ini uangnya tujuh puluh lima ribu ripuah. ",
            "ini kembaliannya ya nak, terimakasih.",
            "terimakasih pak",
            "ini makanannya ya nak",
            "hari ini ayamnya enak sekali ya",
            "iya benar",
            "ini uangnya ya pak, terimakasih."
    };

}
